apiVersion: v1
kind: Secret
metadata:
  name: lightspeed-auth-secret
  namespace: openshift-gitops
  annotations:
    kubernetes.io/service-account.name: openshift-gitops-argocd-application-controller
type: kubernetes.io/service-account-token
